# Generated by Django 6.0.6 on 2026-07-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_user_student_guardians'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='barangay',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='contact_number',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Contact Number of Parent/Guardian'),
        ),
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(blank=True, default='', help_text='Last Name, First Name, Name Extension, Middle Name', max_length=150),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_relationship',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='house_street',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='House No./Street/Sitio/Purok'),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_maiden_name',
            field=models.CharField(blank=True, default='', help_text='Last Name, First Name, Name Extension, Middle Name', max_length=150),
        ),
        migrations.AddField(
            model_name='student',
            name='municipality',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Municipality/City'),
        ),
        migrations.AddField(
            model_name='student',
            name='name_extension',
            field=models.CharField(blank=True, default='', help_text='e.g. Jr., III (SF1 name format)', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='province',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='religious_affiliation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='remarks_code',
            field=models.CharField(blank=True, default='', help_text='SF1 legend codes, e.g. T/O, T/I, CCT, B/A, LWE, ACL', max_length=100, verbose_name='Remarks'),
        ),
    ]
