# Generated by Django 6.0.6 on 2026-07-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_barangay_student_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, help_text='Student photo — used for ID card and face recognition.', null=True, upload_to='student_photos/'),
        ),
    ]
