# Generated by Django 6.0.6 on 2026-07-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='allergies',
            field=models.CharField(blank=True, default='', help_text='Food, medicine, or other allergies.', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='blood_type',
            field=models.CharField(blank=True, default='', help_text='e.g. O+, A-, B+, AB+', max_length=5),
        ),
        migrations.AddField(
            model_name='student',
            name='medical_condition',
            field=models.CharField(blank=True, default='', help_text='Known illness, disability, or special medical condition.', max_length=200),
        ),
    ]
