# Generated by Django 6.0.5 on 2026-07-09 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0005_subjectassignment'),
        ('students', '0002_student_school_year_alter_student_grade_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_quarter', models.DecimalField(decimal_places=2, max_digits=5)),
                ('second_quarter', models.DecimalField(decimal_places=2, max_digits=5)),
                ('third_quarter', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fourth_quarter', models.DecimalField(decimal_places=2, max_digits=5)),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.schoolyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
            ],
        ),
    ]
