# Generated by Django 6.0.6 on 2026-07-24 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_alter_grade_quarters_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='When True, this grade record cannot be modified.'),
        ),
    ]
