# Generated by Django 6.0.6 on 2026-07-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0004_grade_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='When True, this grade has been verified by an authorized user.'),
        ),
    ]
