# Generated by Django 6.0.6 on 2026-07-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_phone_user_profile_picture_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('principal', 'Principal'), ('ict_coordinator', 'ICT Coordinator'), ('teacher', 'Teacher'), ('adviser', 'Adviser Teacher'), ('subject_teacher', 'Subject Teacher'), ('student', 'Student'), ('parent', 'Parent')], default='student', max_length=20),
        ),
    ]
