# Generated by Django 6.0.6 on 2026-07-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_subjectassignment'),
        ('enrollment', '0001_initial'),
        ('students', '0002_student_school_year_alter_student_grade_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-date_enrolled']},
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'school_year'), name='unique_enrollment_per_student_per_year'),
        ),
    ]
