# Generated by Django 6.0.6 on 2026-07-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_alter_enrollment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='semester',
            field=models.CharField(blank=True, choices=[('1', '1st Semester'), ('2', '2nd Semester')], max_length=1, null=True),
        ),
    ]
