# Generated by Django 6.0.6 on 2026-07-17 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_section_course_section_track_strand'),
        ('classrecord', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.PositiveSmallIntegerField(choices=[(1, '1st Quarter'), (2, '2nd Quarter'), (3, '3rd Quarter'), (4, '4th Quarter')])),
                ('component', models.CharField(choices=[('WW', 'Written Work'), ('PT', 'Performance Task'), ('QA', 'Quarterly Assessment')], max_length=2)),
                ('label', models.CharField(help_text='e.g. Quiz 1, PT 2, Term Exam', max_length=100)),
                ('highest_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('subject_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='academics.subjectassignment')),
            ],
            options={
                'ordering': ['quarter', 'component', 'order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='scoreitem',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_items', to='classrecord.assessment'),
        ),
    ]
