# Generated by Django 6.0.6 on 2026-07-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrecord', '0002_assessment_scoreitem_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='competency',
            field=models.CharField(blank=True, default='', help_text='Learning competency this assessment covers, e.g. Identifies the domain and range of a function.', max_length=300),
        ),
    ]
