# Generated by Django 6.0.5 on 2026-07-08 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_gradelevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.gradelevel')),
            ],
        ),
    ]
