# Generated by Django 6.0.6 on 2026-07-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_schoolyear_grading_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='course',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Course (for TVL only)'),
        ),
        migrations.AddField(
            model_name='section',
            name='track_strand',
            field=models.CharField(blank=True, default='', help_text='e.g. Academic - STEM, TVL - ICT (printed on SF1/SF9/SF10 SHS forms)', max_length=100, verbose_name='Track and Strand'),
        ),
    ]
