# Generated by Django 6.0.6 on 2026-07-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_section_course_section_track_strand'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectassignment',
            name='semester',
            field=models.CharField(blank=True, choices=[('1', '1st Semester'), ('2', '2nd Semester')], max_length=1, null=True),
        ),
    ]
