# Generated by Django 6.0.6 on 2026-07-26 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_qrattendancesession'),
        ('students', '0006_student_medical'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceEncoding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.BinaryField(help_text='Pickled LBPH face histogram for this student.')),
                ('trained_at', models.DateTimeField(auto_now=True)),
                ('source_photo', models.CharField(blank=True, default='', help_text='Relative path of the photo used to generate this encoding.', max_length=200)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_encoding', to='students.student')),
            ],
        ),
    ]
